name:                spjdl
version:             0.2.7.5
github:              "nobsun/spjdl"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@gmail.com"
copyright:           "Copyright: (c) 2019 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/spjdl#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- markdown-unlit
- doctest
- bytestring
- utf8-string
- hspec
- main-tester

library:
  source-dirs: src

executables:
  spjdl-exe:
    main:                Main.hs
    source-dirs:         app
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - spjdl

tests:
  spjdl-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - spjdl

  spjdl-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - spjdl
